version : '3.3'

services:
    lb:
        image: haproxy:1.7
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy:ro
    nodeapp1:
        image: nodeapp
        environment:
            - APPID=1111
    nodeapp2:
        image: nodeapp
        environment:
            - APPID=2222
    nodeapp3:
        image: nodeapp
        environment:
            - APPID=3333
    nodeapp4:
        image: nodeapp
        environment:
            - APPID=4444
